version: '3.5'

services:
  api:
    image: sensors-api
    build:
      context: .
      target: sensors_api
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: on-failure

  simulator:
    image: sensors-simulator
    build:
      context: .
      target: sensors_simulator
    env_file:
      - .env
    environment:
      HOST: api
    command: [ "--devices", "10", "--base-url", "http://api:8000" ]
    depends_on:
      - api

  db:
    image: postgres:14.2-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env
    restart: always

volumes:
  pgdata:
